const props = {
  active: { type: Boolean },
  visible: { type: Boolean },
  x: { type: Number },
  y: { type: Number },
  x1: { type: Number },
  y1: { type: Number },
  x2: { type: Number },
  y2: { type: Number },
  x3: { type: Number },
  y3: { type: Number },
  points: { type: Array },
  rotation: { type: Number },
  origin: { type: Number },
  originX: { type: Number },
  originY: { type: Number },
  scale: { type: Number },
  scaleX: { type: Number },
  scaleY: { type: Number },
  width: { type: Number },
  height: { type: Number },
  leftWidth: { type: Number },
  rightWidth: { type: Number },
  topHeight: { type: Number },
  bottomHeight: { type: Number },
  radius: { type: Number },
  displayWidth: { type: Number },
  displayHeight: { type: Number },
  displayOriginX: { type: Number },
  displayOriginY: { type: Number },
  dropZone: { type: Boolean },
  flipX: { type: Boolean },
  flipY: { type: Boolean },
  depth: { type: Number },
  alpha: { type: Number },
  blendMode: { type: [Number, String] },
  lighting: { type: Boolean },
  intensity: { type: Number },
  tint: { type: Number },
  text: { type: [String, Number] },
  texture: { type: String },
  frame: { type: [Number, String] },
  color: { type: Number },
  fillColor: { type: Number },
  fillAlpha: { type: Number },
  lineWidth: { type: Number },
  strokeColor: { type: Number },
  strokeAlpha: { type: Number },
  style: { type: Object },
  lineSpacing: { type: Number },
  padding: { type: [Number, Object] },
  collision: { type: [Number, Array] },
  collisionByProperty: { type: Object },
  play: { type: [String, Object] },
  scrollFactor: { type: Number },
  scrollFactorX: { type: Number },
  scrollFactorY: { type: Number },
  // Body
  enable: { type: Boolean },
  immovable: { type: Boolean },
  moves: { type: Boolean },
  bounceX: { type: Number },
  bounceY: { type: Number },
  drag: { type: Number },
  dragX: { type: Number },
  dragY: { type: Number },
  gravityX: { type: Number },
  gravityY: { type: Number },
  frictionX: { type: Number },
  frictionY: { type: Number },
  velocityX: { type: Number },
  velocityY: { type: Number },
  maxVelocityX: { type: Number },
  maxVelocityY: { type: Number },
  accelerationX: { type: Number },
  accelerationY: { type: Number },
  offsetX: { type: Number },
  offsetY: { type: Number },
  collideWorldBounds: { type: Boolean },
  // Tween
  tween: { type: Object },
  tweens: { type: Array },
  timeline: { type: Object },
  // FX
  post: { type: Boolean },
  quality: { type: Number },
  steps: { type: Number },
  strength: { type: Number },
  distance: { type: Number },
  outerStrength: { type: Number },
  innerStrength: { type: Number },
  knockout: { type: Boolean },
  decay: { type: Number },
  power: { type: Number },
  samples: { type: Number },
  amount: { type: Number },
  // Bokeh
  contrast: { type: Number },
  // Wipe
  reveal: { type: Number },
  progress: { type: Number },
  wipeWidth: { type: Number },
  direction: { type: Number },
  axis: { type: Number },
  // ColorMatrix
  brightness: { type: Number },
  saturate: { type: Number },
  desaturate: { type: Number },
  hue: { type: Number },
  grayscale: { type: Number },
  blackWhite: { type: Boolean },
  negative: { type: Boolean },
  desaturateLuminance: { type: Boolean },
  sepia: { type: Boolean },
  night: { type: Number },
  lsd: { type: Boolean },
  brown: { type: Boolean },
  vintagePinhole: { type: Boolean },
  kodachrome: { type: Boolean },
  technicolor: { type: Boolean },
  polaroid: { type: Boolean },
  shiftToBGR: { type: Boolean },
}
export default props
export const gameObjectProps = {
  tween: props.tween,
  tweens: props.tweens,
  timeline: props.timeline,
  active: props.active,
  visible: props.visible,
  x: props.x,
  y: props.y,
  rotation: props.rotation,
  origin: props.origin,
  originX: props.originX,
  originY: props.originY,
  displayOriginX: props.displayOriginX,
  displayOriginY: props.displayOriginY,
  scale: props.scale,
  scaleX: props.scaleX,
  scaleY: props.scaleY,
  displayWidth: props.displayWidth,
  displayHeight: props.displayHeight,
  scrollFactor: props.scrollFactor,
  scrollFactorX: props.scrollFactorX,
  scrollFactorY: props.scrollFactorY,
  dropZone: props.dropZone,
  depth: props.depth,
  alpha: props.alpha,
  blendMode: props.blendMode,
  lighting: props.lighting,
} as const

// TODO: remove later
export const mapProps = () => null
